{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjmenuactiondelegate\/canperform(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjmenuactiondelegate\/canperform(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate\/canPerform(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"canPerform:"}],"role":"symbol","title":"canPerform(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:@M@BJOTPViewController@objc(pl)BJMenuActionDelegate(im)canPerform:","required":true,"modules":[{"name":"BJOTPViewController"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJMenuActionDelegate":{"role":"symbol","title":"BJMenuActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJMenuActionDelegate"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJMenuActionDelegate"}],"url":"\/documentation\/bjotpviewcontroller\/bjmenuactiondelegate"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJMenuActionDelegate/canPerform(_:)":{"navigatorTitle":[{"kind":"identifier","text":"canPerform:"}],"role":"symbol","title":"canPerform(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate\/canPerform(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjmenuactiondelegate\/canperform(_:)"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canPerform:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerform:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canPerform:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SEL","preciseIdentifier":"c:e"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate\/title","value":"BJMenuActionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate\/fragments","value":[{"kind":"identifier","text":"BJMenuActionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate~1canPerform(_:)\/title","value":"canPerform:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate~1canPerform(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerform:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}