{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"otp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController","text":"BJOTPViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"otp","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The full otp string entered."}]}]},{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The otp view controller."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method will get called only after the validation is successful, i.e., after the user has filled all the text fields."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Badhan Ganesh"}]}],"type":"aside","name":"Author"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate\/authenticate(_:from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate\/authenticate(_:from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/authenticate(_:from:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method gets called when the user has entered all the otp characters and tapped the authenticate button."},{"type":"text","text":" "},{"type":"text","text":"Use this delegate method to make API calls, show loading animation in "},{"type":"codeVoice","code":"viewController"},{"type":"text","text":", do whatever you want."},{"type":"text","text":" "},{"type":"text","text":"You can dismiss (if presented) the "},{"type":"codeVoice","code":"viewController"},{"type":"text","text":" when you’re done."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"authenticate:from:"}],"role":"symbol","title":"authenticate(_:from:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@BJOTPViewController@objc(pl)BJOTPViewControllerDelegate(im)authenticate:from:","required":true,"modules":[{"name":"BJOTPViewController"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewControllerDelegate":{"role":"symbol","title":"BJOTPViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewControllerDelegate"}],"abstract":[{"type":"text","text":"This protocol declares methods that are essential to use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"},{"type":"text","text":". They are used to handle button taps that happen during various scenarios, for example close button tap action."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewControllerDelegate"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewControllerDelegate/authenticate(_:from:)":{"navigatorTitle":[{"kind":"identifier","text":"authenticate:from:"}],"role":"symbol","title":"authenticate(_:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method gets called when the user has entered all the otp characters and tapped the authenticate button."},{"type":"text","text":" "},{"type":"text","text":"Use this delegate method to make API calls, show loading animation in "},{"type":"codeVoice","code":"viewController"},{"type":"text","text":", do whatever you want."},{"type":"text","text":" "},{"type":"text","text":"You can dismiss (if presented) the "},{"type":"codeVoice","code":"viewController"},{"type":"text","text":" when you’re done."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/authenticate(_:from:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate\/authenticate(_:from:)"},"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"authenticate:from:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticate:from:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"authenticate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"otp"},{"kind":"text","text":" "},{"kind":"identifier","text":"from:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController","text":"BJOTPViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate\/title","value":"BJOTPViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"BJOTPViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1authenticate(_:from:)\/title","value":"authenticate:from:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1authenticate(_:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticate:from:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}