{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Setting up the otp view controller is very easy and straightforward. Check below to learn how to do it. Thank you."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"BJOTPViewController","title":"BJOTPViewController","symbolKind":"module","role":"collection","modules":[{"name":"BJOTPViewController"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Getting-Started","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage"]},{"title":"Protocols","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate"]}],"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJMenuActionDelegate":{"role":"symbol","title":"BJMenuActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJMenuActionDelegate"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJMenuActionDelegate"}],"url":"\/documentation\/bjotpviewcontroller\/bjmenuactiondelegate"},"doc://BJOTPViewController/documentation/BJOTPViewController/Getting-Started":{"role":"article","title":"Getting Started - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Getting-Started","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/getting-started"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Getting-Started","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage"]},{"title":"Protocols","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate"]}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate\/title","value":"BJMenuActionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate\/fragments","value":[{"kind":"identifier","text":"BJMenuActionDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}