{"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/bjmenuactiondelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/bjmenuactiondelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/BJMenuActionDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/canPerform(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"BJOTPViewController"}],"role":"collectionGroup","title":"BJMenuActionDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/canPerform(_:)":{"role":"symbol","title":"canPerform(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPerform"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Selector","preciseIdentifier":"s:10ObjectiveC8SelectorV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/canPerform(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canPerform:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/canperform(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/canPerform(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1canPerform(_:)\/title","value":"canPerform:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1canPerform(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canPerform:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}