{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is optional. In case of nil, the label won’t be constructed at all. So make sure to set a string, or leave it as it is ("},{"type":"codeVoice","code":"nil"},{"type":"text","text":")."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Badhan Ganesh"}]}],"type":"aside","name":"Author"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footertitle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footertitle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerTitle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The title of the footer label which comes below the authenticate button."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"footerTitle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController(py)footerTitle","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"footerTitle"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/footerTitle":{"role":"symbol","title":"footerTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The title of the footer label which comes below the authenticate button."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"footerTitle"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footertitle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"footerTitle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"footerTitle"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *"},{"kind":"identifier","text":"footerTitle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerTitle\/title","value":"footerTitle"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerTitle\/fragments","value":[{"kind":"identifier","text":"footerTitle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}