{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This color will be applied only when "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldFooterBehaveAsButton"},{"type":"text","text":" is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":". Default gray color will be used otherwise. The accent color will be used by default if there is no "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerButtonColor"},{"type":"text","text":" supplied."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Badhan Ganesh"}]}],"type":"aside","name":"Author"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footerbuttoncolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footerbuttoncolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerButtonColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The color of the footer."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"title":"footerButtonColor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController(py)footerButtonColor","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"footerButtonColor"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldFooterBehaveAsButton":{"role":"symbol","title":"shouldFooterBehaveAsButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldFooterBehaveAsButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks whether the footer should behave as a button or just a normal label. Button will pass the action to the delegate method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/didTap(footer:from:)"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldFooterBehaveAsButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldFooterBehaveAsButton"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldfooterbehaveasbutton"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewControllerDelegate/didTap(footer:from:)":{"navigatorTitle":[{"kind":"identifier","text":"didTapWithFooter:from:"}],"role":"symbol","title":"didTap(footer:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This delegate method will get called when the footer button at the bottom is tapped. Use this to resend one time code from the server"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/didTap(footer:from:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate\/didtap(footer:from:)"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/footerButtonColor":{"role":"symbol","title":"footerButtonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color of the footer."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerButtonColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"footerButtonColor"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footerbuttoncolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"footerButtonColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"footerButtonColor"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *"},{"kind":"identifier","text":"footerButtonColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldFooterBehaveAsButton\/title","value":"shouldFooterBehaveAsButton"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldFooterBehaveAsButton\/fragments","value":[{"kind":"identifier","text":"shouldFooterBehaveAsButton"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1didTap(footer:from:)\/title","value":"didTapWithFooter:from:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1didTap(footer:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapWithFooter:from:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerButtonColor\/title","value":"footerButtonColor"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerButtonColor\/fragments","value":[{"kind":"identifier","text":"footerButtonColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}