{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hapticsEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Badhan Ganesh"}]}],"type":"aside","name":"Author"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/hapticsenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/hapticsenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hapticsEnabled","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Uses haptics for touches, interactions, successes and errors within the OTP view controller."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hapticsEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"hapticsEnabled","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController(py)hapticsEnabled","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"hapticsEnabled"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/hapticsEnabled":{"role":"symbol","title":"hapticsEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hapticsEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Uses haptics for touches, interactions, successes and errors within the OTP view controller."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hapticsEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hapticsEnabled"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/hapticsenabled"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hapticsEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hapticsEnabled"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"hapticsEnabled"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1hapticsEnabled\/title","value":"hapticsEnabled"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1hapticsEnabled\/fragments","value":[{"kind":"identifier","text":"hapticsEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}