{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(coder:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController(im)initWithCoder:","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/init(coder:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}