{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"presentationController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/presentationcontrollerdidattempttodismiss(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/presentationcontrollerdidattempttodismiss(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/presentationControllerDidAttemptToDismiss(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIAdaptivePresentationControllerDelegate.presentationControllerDidAttemptToDismiss(_:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"title":"presentationControllerDidAttemptToDismiss(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@BJOTPViewController@objc(cs)BJOTPViewController(im)presentationControllerDidAttemptToDismiss:","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UIAdaptivePresentationControllerDelegate-Implementations"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/UIAdaptivePresentationControllerDelegate-Implementations":{"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UIAdaptivePresentationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"},"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/presentationControllerDidAttemptToDismiss(_:)":{"role":"symbol","title":"presentationControllerDidAttemptToDismiss(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/presentationControllerDidAttemptToDismiss(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/presentationcontrollerdidattempttodismiss(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"presentationControllerDidAttemptToDismiss:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"presentationController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1presentationControllerDidAttemptToDismiss(_:)\/title","value":"presentationControllerDidAttemptToDismiss:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1presentationControllerDidAttemptToDismiss(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}