{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scene"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":" "},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":" "},{"kind":"internalParam","text":"connectionOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/scene(_:willconnectto:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/scene(_:willconnectto:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/scene(_:willConnectTo:options:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISceneDelegate.scene(_:willConnectTo:options:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}],"role":"symbol","title":"scene(_:willConnectTo:options:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@BJOTPViewController@objc(cs)BJOTPViewController(im)scene:willConnectToSession:options:","extendedModule":"BJOTPViewController","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UISceneDelegate-Implementations"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/scene(_:willConnectTo:options:)":{"role":"symbol","title":"scene(_:willConnectTo:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scene"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":", "},{"kind":"externalParam","text":"willConnectTo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/scene(_:willConnectTo:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"scene:willConnectToSession:options:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/scene(_:willconnectto:options:)"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/UISceneDelegate-Implementations":{"role":"collectionGroup","title":"UISceneDelegate Implementations","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UISceneDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uiscenedelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"scene:willConnectToSession:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scene:willConnectToSession:options:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"scene:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScene","preciseIdentifier":"c:objc(cs)UIScene"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"scene"},{"kind":"text","text":" "},{"kind":"identifier","text":"willConnectToSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISceneSession","preciseIdentifier":"c:objc(cs)UISceneSession"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISceneConnectionOptions","preciseIdentifier":"c:objc(cs)UISceneConnectionOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"connectionOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1scene(_:willConnectTo:options:)\/title","value":"scene:willConnectToSession:options:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1scene(_:willConnectTo:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"scene:willConnectToSession:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}