{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"But be careful when setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" as this might not be the best user experiece all the time. This does not give the user the control of what code to paste."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Some\/most users may prefer quick submission and verification of OTP code without any extra clicks or taps. This saves a quite a few milliseconds from them."}]},{"type":"paragraph","inlineContent":[{"type":"strong","inlineContent":[{"type":"text","text":"Note:"}]},{"type":"text","text":" OTP code won’t be pasted for the same string copied over and over. Clipboard will be checked when the app comes to foreground, and when the view controller’s view finished appearing."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Badhan Ganesh"}]}],"type":"aside","name":"Author"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldautomaticallypastecopiedstringfromclipboard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldautomaticallypastecopiedstringfromclipboard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldAutomaticallyPasteCopiedStringFromClipboard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will automatically paste compatible text that is present in the clipboard and call the "},{"type":"codeVoice","code":"authenticate"},{"type":"text","text":" delegate method without asking any questions. This property will take precedence over "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard"},{"type":"text","text":" property."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"shouldAutomaticallyPasteCopiedStringFromClipboard","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController(py)shouldAutomaticallyPasteCopiedStringFromClipboard","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldPromptUserToPasteCopiedStringFromClipboard":{"role":"symbol","title":"shouldPromptUserToPasteCopiedStringFromClipboard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will show an alert to the user whenever a compatible text is copied to clipboard asking whether or not to paste the same. Yes or No option will be provided."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldpromptusertopastecopiedstringfromclipboard"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldAutomaticallyPasteCopiedStringFromClipboard":{"role":"symbol","title":"shouldAutomaticallyPasteCopiedStringFromClipboard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will automatically paste compatible text that is present in the clipboard and call the "},{"type":"codeVoice","code":"authenticate"},{"type":"text","text":" delegate method without asking any questions. This property will take precedence over "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard"},{"type":"text","text":" property."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldAutomaticallyPasteCopiedStringFromClipboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldautomaticallypastecopiedstringfromclipboard"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldPromptUserToPasteCopiedStringFromClipboard\/title","value":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldPromptUserToPasteCopiedStringFromClipboard\/fragments","value":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldAutomaticallyPasteCopiedStringFromClipboard\/title","value":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldAutomaticallyPasteCopiedStringFromClipboard\/fragments","value":[{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}