{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Tapping “Yes” will auto-fill all the textfields with copied text and will call the "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/authenticate(_:from:)"},{"type":"text","text":" delegate method."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Pop-up won’t be shown for the same string copied over and over. Clipboard will be checked when the app comes to foreground, and when the view controller’s view finished appearing."}]},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Badhan Ganesh"}]}],"type":"aside","name":"Author"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldpromptusertopastecopiedstringfromclipboard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldpromptusertopastecopiedstringfromclipboard"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will show an alert to the user whenever a compatible text is copied to clipboard asking whether or not to paste the same. Yes or No option will be provided."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"shouldPromptUserToPasteCopiedStringFromClipboard","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController(py)shouldPromptUserToPasteCopiedStringFromClipboard","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldPromptUserToPasteCopiedStringFromClipboard":{"role":"symbol","title":"shouldPromptUserToPasteCopiedStringFromClipboard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will show an alert to the user whenever a compatible text is copied to clipboard asking whether or not to paste the same. Yes or No option will be provided."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldpromptusertopastecopiedstringfromclipboard"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewControllerDelegate/authenticate(_:from:)":{"navigatorTitle":[{"kind":"identifier","text":"authenticate:from:"}],"role":"symbol","title":"authenticate(_:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method gets called when the user has entered all the otp characters and tapped the button."},{"type":"text","text":" "},{"type":"text","text":"Use this delegate method to make API calls, show loading animation in "},{"type":"codeVoice","code":"viewController"},{"type":"text","text":", do whatever you want."},{"type":"text","text":" "},{"type":"text","text":"You can dismiss (if presented) the "},{"type":"codeVoice","code":"viewController"},{"type":"text","text":" when you’re done."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/authenticate(_:from:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate\/authenticate(_:from:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldPromptUserToPasteCopiedStringFromClipboard\/title","value":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldPromptUserToPasteCopiedStringFromClipboard\/fragments","value":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1authenticate(_:from:)\/title","value":"authenticate:from:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1authenticate(_:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"authenticate:from:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}