{"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UIAdaptivePresentationControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/presentationControllerDidAttemptToDismiss(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"BJOTPViewController"}],"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/presentationControllerDidAttemptToDismiss(_:)":{"role":"symbol","title":"presentationControllerDidAttemptToDismiss(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPresentationController","preciseIdentifier":"c:objc(cs)UIPresentationController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/presentationControllerDidAttemptToDismiss(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/presentationcontrollerdidattempttodismiss(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/presentationControllerDidAttemptToDismiss(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1presentationControllerDidAttemptToDismiss(_:)\/title","value":"presentationControllerDidAttemptToDismiss:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1presentationControllerDidAttemptToDismiss(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationControllerDidAttemptToDismiss:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}