{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This is intended to be a drag and drop view controller that gets the work done quickly, in and out, that’s it. No fancy customizations, no cluttering the screen with tons of UI elements and crazy colors. You’ll be good to go with the default settings."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/BJOTPViewController\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate","doc:\/\/BJOTPViewController\/objc(pl)NSCoding","doc:\/\/BJOTPViewController\/objc(pl)NSExtensionRequestHandling","doc:\/\/BJOTPViewController\/objc(pl)NSObject","doc:\/\/BJOTPViewController\/s7CVarArgP","doc:\/\/BJOTPViewController\/s28CustomDebugStringConvertibleP","doc:\/\/BJOTPViewController\/s23CustomStringConvertibleP","doc:\/\/BJOTPViewController\/SQ","doc:\/\/BJOTPViewController\/SH","doc:\/\/BJOTPViewController\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/BJOTPViewController\/objc(pl)UIAdaptivePresentationControllerDelegate","doc:\/\/BJOTPViewController\/objc(pl)UIAppearanceContainer","doc:\/\/BJOTPViewController\/objc(pl)UIContentContainer","doc:\/\/BJOTPViewController\/objc(pl)UIFocusEnvironment","doc:\/\/BJOTPViewController\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/BJOTPViewController\/objc(pl)UIResponderStandardEditActions","doc:\/\/BJOTPViewController\/objc(pl)UISceneDelegate","doc:\/\/BJOTPViewController\/objc(pl)UIStateRestoring","doc:\/\/BJOTPViewController\/objc(pl)UITextFieldDelegate","doc:\/\/BJOTPViewController\/objc(pl)UITraitEnvironment","doc:\/\/BJOTPViewController\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"title":"BJOTPViewController","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController","modules":[{"name":"BJOTPViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(coder:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(withHeading:withNumberOfCharacters:delegate:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/accentColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/authenticateButtonColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/authenticateButtonTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/brandImage","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/closeButtonColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/currentTextFieldColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/delegate","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerButtonColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hapticsEnabled","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hideLabelsWhenEditing","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/openKeyboadDuringStartup","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/primaryHeaderTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/secondaryHeaderTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldAutomaticallyPasteCopiedStringFromClipboard","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldFooterBehaveAsButton","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard"]},{"title":"Instance Methods","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/touchesEnded(_:with:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidAppear(_:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidDisappear(_:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidLoad()","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillDisappear(_:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillLayoutSubviews()","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillTransition(to:with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/BJMenuActionDelegate-Implementations","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UIAdaptivePresentationControllerDelegate-Implementations","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UISceneDelegate-Implementations","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UITextFieldDelegate-Implementations"],"generated":true}],"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/viewWillTransition(to:with:)":{"role":"symbol","title":"viewWillTransition(to:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillTransition(to:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/viewwilltransition(to:with:)"},"doc://BJOTPViewController/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/viewDidAppear(_:)":{"role":"symbol","title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/viewdidappear(_:)"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/viewDidLoad()":{"role":"symbol","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidLoad()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/viewdidload()"},"doc://BJOTPViewController/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIPasteConfigurationSupporting"},"doc://BJOTPViewController/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIContentContainer"},"doc://BJOTPViewController/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/BJOTPViewController\/objc(cs)UIViewController"},"doc://BJOTPViewController/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/BJOTPViewController\/objc(pl)NSObject"},"doc://BJOTPViewController/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/BJOTPViewController\/objc(pl)NSCoding"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/UIAdaptivePresentationControllerDelegate-Implementations":{"role":"collectionGroup","title":"UIAdaptivePresentationControllerDelegate Implementations","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UIAdaptivePresentationControllerDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uiadaptivepresentationcontrollerdelegate-implementations"},"doc://BJOTPViewController/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/BJOTPViewController\/s23CustomStringConvertibleP"},"doc://BJOTPViewController/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/BJOTPViewController\/objc(pl)NSExtensionRequestHandling"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/secondaryHeaderTitle":{"role":"symbol","title":"secondaryHeaderTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryHeaderTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The title of the secondary header which comes below the primary header."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/secondaryHeaderTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"secondaryHeaderTitle"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/secondaryheadertitle"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/footerButtonColor":{"role":"symbol","title":"footerButtonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color of the footer."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerButtonColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"footerButtonColor"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footerbuttoncolor"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/authenticateButtonTitle":{"role":"symbol","title":"authenticateButtonTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticateButtonTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The title of the authenticate button."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/authenticateButtonTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticateButtonTitle"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/authenticatebuttontitle"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/currentTextFieldColor":{"role":"symbol","title":"currentTextFieldColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentTextFieldColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The currently focused text field color. This color will appear faded (less opacity) to look good instead of being saturated."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/currentTextFieldColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentTextFieldColor"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/currenttextfieldcolor"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/UISceneDelegate-Implementations":{"role":"collectionGroup","title":"UISceneDelegate Implementations","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UISceneDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uiscenedelegate-implementations"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/hideLabelsWhenEditing":{"role":"symbol","title":"hideLabelsWhenEditing","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hideLabelsWhenEditing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Set whether the primary, secondary labels are to be hidden during editing, i.e., when the keyboard is open."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hideLabelsWhenEditing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hideLabelsWhenEditing"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/hidelabelswhenediting"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/accentColor":{"role":"symbol","title":"accentColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"accentColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color that will be used overall for the UI elements. Set this if you want a common color to be used in the view controller instead of worrying about each UI element’s color."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/accentColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"accentColor"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/accentcolor"},"doc://BJOTPViewController/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UITraitEnvironment"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJMenuActionDelegate":{"role":"symbol","title":"BJMenuActionDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJMenuActionDelegate"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJMenuActionDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJMenuActionDelegate"}],"url":"\/documentation\/bjotpviewcontroller\/bjmenuactiondelegate"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/touchesEnded(_:with:)":{"role":"symbol","title":"touchesEnded(_:with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesEnded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UITouch","preciseIdentifier":"c:objc(cs)UITouch"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Call this method to dismiss the keyboard, and reset the position of the master stack view to its original position, and reset all labels’ alpha to 1.0."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/touchesEnded(_:with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"touchesEnded:withEvent:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/touchesended(_:with:)"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/hapticsEnabled":{"role":"symbol","title":"hapticsEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hapticsEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Uses haptics for touches, interactions, successes and errors within the OTP view controller."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hapticsEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hapticsEnabled"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/hapticsenabled"},"doc://BJOTPViewController/objc(pl)UITextFieldDelegate":{"type":"unresolvable","title":"UIKit.UITextFieldDelegate","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UITextFieldDelegate"},"doc://BJOTPViewController/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIResponderStandardEditActions"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/viewWillDisappear(_:)":{"role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/viewwilldisappear(_:)"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/viewWillLayoutSubviews()":{"role":"symbol","title":"viewWillLayoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillLayoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillLayoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillLayoutSubviews"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/viewwilllayoutsubviews()"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/footerTitle":{"role":"symbol","title":"footerTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"footerTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The title of the footer label which comes below the authenticate button."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"footerTitle"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/footertitle"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldFooterBehaveAsButton":{"role":"symbol","title":"shouldFooterBehaveAsButton","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldFooterBehaveAsButton"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Asks whether the footer should behave as a button or just a normal label. Button will pass the action to the delegate method "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/didTap(footer:from:)"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldFooterBehaveAsButton","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldFooterBehaveAsButton"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldfooterbehaveasbutton"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/primaryHeaderTitle":{"role":"symbol","title":"primaryHeaderTitle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryHeaderTitle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The title of the primary header which stays above the OTP textfields."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/primaryHeaderTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"primaryHeaderTitle"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/primaryheadertitle"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/init(withHeading:withNumberOfCharacters:delegate:)":{"role":"symbol","title":"init(withHeading:withNumberOfCharacters:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withHeading"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withNumberOfCharacters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewControllerDelegate","preciseIdentifier":"c:@M@BJOTPViewController@objc(pl)BJOTPViewControllerDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The init method to use to construct "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(withHeading:withNumberOfCharacters:delegate:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithHeading:withNumberOfCharacters:delegate:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/init(withheading:withnumberofcharacters:delegate:)"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewControllerDelegate","preciseIdentifier":"c:@M@BJOTPViewController@objc(pl)BJOTPViewControllerDelegate"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The delegate object that is responsible for performing the actual authentication\/verification process (with server via api call or whatever)"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/delegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/delegate"},"doc://BJOTPViewController/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/BJOTPViewController\/SQ"},"doc://BJOTPViewController/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/BJOTPViewController\/s7CVarArgP"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldAutomaticallyPasteCopiedStringFromClipboard":{"role":"symbol","title":"shouldAutomaticallyPasteCopiedStringFromClipboard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will automatically paste compatible text that is present in the clipboard and call the "},{"type":"codeVoice","code":"authenticate"},{"type":"text","text":" delegate method without asking any questions. This property will take precedence over "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard"},{"type":"text","text":" property."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldAutomaticallyPasteCopiedStringFromClipboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldautomaticallypastecopiedstringfromclipboard"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/brandImage":{"role":"symbol","title":"brandImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"brandImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The image (logo) of your brand that you would like to add to the top of the OTP UI."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/brandImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"brandImage"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/brandimage"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/closeButtonColor":{"role":"symbol","title":"closeButtonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color of the close button."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/closeButtonColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"closeButtonColor"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/closebuttoncolor"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/shouldPromptUserToPasteCopiedStringFromClipboard":{"role":"symbol","title":"shouldPromptUserToPasteCopiedStringFromClipboard","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Setting this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" will show an alert to the user whenever a compatible text is copied to clipboard asking whether or not to paste the same. Yes or No option will be provided."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/shouldpromptusertopastecopiedstringfromclipboard"},"doc://BJOTPViewController/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIUserActivityRestoring"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/authenticateButtonColor":{"role":"symbol","title":"authenticateButtonColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticateButtonColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The color of the authenticate button."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/authenticateButtonColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"authenticateButtonColor"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/authenticatebuttoncolor"},"doc://BJOTPViewController/objc(pl)UIAdaptivePresentationControllerDelegate":{"type":"unresolvable","title":"UIKit.UIAdaptivePresentationControllerDelegate","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIAdaptivePresentationControllerDelegate"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/BJMenuActionDelegate-Implementations":{"role":"collectionGroup","title":"BJMenuActionDelegate Implementations","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/BJMenuActionDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/bjmenuactiondelegate-implementations"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/init(coder:)"},"doc://BJOTPViewController/objc(pl)UISceneDelegate":{"type":"unresolvable","title":"UIKit.UISceneDelegate","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UISceneDelegate"},"doc://BJOTPViewController/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIAppearanceContainer"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/UITextFieldDelegate-Implementations":{"role":"collectionGroup","title":"UITextFieldDelegate Implementations","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UITextFieldDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/uitextfielddelegate-implementations"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/viewdiddisappear(_:)"},"doc://BJOTPViewController/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIStateRestoring"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController/openKeyboadDuringStartup":{"role":"symbol","title":"openKeyboadDuringStartup","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"openKeyboadDuringStartup"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Setting this to true opens up the keyboard for the very first text field."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/openKeyboadDuringStartup","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"openKeyboadDuringStartup"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller\/openkeyboadduringstartup"},"doc://BJOTPViewController/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/BJOTPViewController\/objc(pl)UIFocusEnvironment"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewControllerDelegate/didTap(footer:from:)":{"navigatorTitle":[{"kind":"identifier","text":"didTapWithFooter:from:"}],"role":"symbol","title":"didTap(footer:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didTap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"footer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BJOTPViewController","preciseIdentifier":"c:@M@BJOTPViewController@objc(cs)BJOTPViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This delegate method will get called when the footer button at the bottom is tapped. Use this to resend one time code from the server"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate\/didTap(footer:from:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate\/didtap(footer:from:)"},"doc://BJOTPViewController/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/BJOTPViewController\/s28CustomDebugStringConvertibleP"},"doc://BJOTPViewController/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/BJOTPViewController\/SH"},"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/accentColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/authenticateButtonColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/authenticateButtonTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/brandImage","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/closeButtonColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/currentTextFieldColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/delegate","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerButtonColor","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/footerTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hapticsEnabled","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/hideLabelsWhenEditing","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/openKeyboadDuringStartup","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/primaryHeaderTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/secondaryHeaderTitle","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldAutomaticallyPasteCopiedStringFromClipboard","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldFooterBehaveAsButton","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/shouldPromptUserToPasteCopiedStringFromClipboard"]},{"title":"Instance Methods","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(coder:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/init(withHeading:withNumberOfCharacters:delegate:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/touchesEnded(_:with:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidAppear(_:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidDisappear(_:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewDidLoad()","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillDisappear(_:)","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillLayoutSubviews()","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/viewWillTransition(to:with:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/BJMenuActionDelegate-Implementations","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UIAdaptivePresentationControllerDelegate-Implementations","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UISceneDelegate-Implementations","doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController\/UITextFieldDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1secondaryHeaderTitle\/title","value":"secondaryHeaderTitle"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1secondaryHeaderTitle\/fragments","value":[{"kind":"identifier","text":"secondaryHeaderTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerButtonColor\/title","value":"footerButtonColor"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerButtonColor\/fragments","value":[{"kind":"identifier","text":"footerButtonColor"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1authenticateButtonTitle\/title","value":"authenticateButtonTitle"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1authenticateButtonTitle\/fragments","value":[{"kind":"identifier","text":"authenticateButtonTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1currentTextFieldColor\/title","value":"currentTextFieldColor"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1currentTextFieldColor\/fragments","value":[{"kind":"identifier","text":"currentTextFieldColor"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1hideLabelsWhenEditing\/title","value":"hideLabelsWhenEditing"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1hideLabelsWhenEditing\/fragments","value":[{"kind":"identifier","text":"hideLabelsWhenEditing"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1accentColor\/title","value":"accentColor"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1accentColor\/fragments","value":[{"kind":"identifier","text":"accentColor"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate\/title","value":"BJMenuActionDelegate"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJMenuActionDelegate\/fragments","value":[{"kind":"identifier","text":"BJMenuActionDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1touchesEnded(_:with:)\/title","value":"touchesEnded:withEvent:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1touchesEnded(_:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesEnded:withEvent:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1hapticsEnabled\/title","value":"hapticsEnabled"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1hapticsEnabled\/fragments","value":[{"kind":"identifier","text":"hapticsEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewWillLayoutSubviews()\/title","value":"viewWillLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewWillLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillLayoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerTitle\/title","value":"footerTitle"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1footerTitle\/fragments","value":[{"kind":"identifier","text":"footerTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldFooterBehaveAsButton\/title","value":"shouldFooterBehaveAsButton"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldFooterBehaveAsButton\/fragments","value":[{"kind":"identifier","text":"shouldFooterBehaveAsButton"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1primaryHeaderTitle\/title","value":"primaryHeaderTitle"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1primaryHeaderTitle\/fragments","value":[{"kind":"identifier","text":"primaryHeaderTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1init(withHeading:withNumberOfCharacters:delegate:)\/title","value":"initWithHeading:withNumberOfCharacters:delegate:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1init(withHeading:withNumberOfCharacters:delegate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithHeading:withNumberOfCharacters:delegate:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldAutomaticallyPasteCopiedStringFromClipboard\/title","value":"shouldAutomaticallyPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldAutomaticallyPasteCopiedStringFromClipboard\/fragments","value":[{"kind":"identifier","text":"shouldAutomaticallyPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1brandImage\/title","value":"brandImage"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1brandImage\/fragments","value":[{"kind":"identifier","text":"brandImage"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1closeButtonColor\/title","value":"closeButtonColor"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1closeButtonColor\/fragments","value":[{"kind":"identifier","text":"closeButtonColor"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldPromptUserToPasteCopiedStringFromClipboard\/title","value":"shouldPromptUserToPasteCopiedStringFromClipboard"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1shouldPromptUserToPasteCopiedStringFromClipboard\/fragments","value":[{"kind":"identifier","text":"shouldPromptUserToPasteCopiedStringFromClipboard"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1authenticateButtonColor\/title","value":"authenticateButtonColor"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1authenticateButtonColor\/fragments","value":[{"kind":"identifier","text":"authenticateButtonColor"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1openKeyboadDuringStartup\/title","value":"openKeyboadDuringStartup"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController~1openKeyboadDuringStartup\/fragments","value":[{"kind":"identifier","text":"openKeyboadDuringStartup"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1didTap(footer:from:)\/title","value":"didTapWithFooter:from:"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate~1didTap(footer:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didTapWithFooter:from:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}