{"primaryContentSections":[{"kind":"content","content":[{"anchor":"","level":2,"type":"heading","text":""},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"banner.png"}]},{"anchor":"What-is-BJOTPViewController?","level":2,"type":"heading","text":"What is BJOTPViewController?"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A very simple and neat-looking view controller that lets you type in OTPs quick and easy."}]},{"anchor":"Supports","level":2,"type":"heading","text":"Supports"},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ iOS 11.0+"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Swift 4.0+"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Portrait | Landscape"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Light Mode | Dark Mode"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ iOS | iPadOS | macOS (Catalyst)"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Objective-C (Xcode 11.4 onwards)"}]},{"anchor":"Features","level":2,"type":"heading","text":"Features"},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Keyboard handling"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Copy-Paste handling"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Auto-fill from Messages app"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Apple-inspired Clean User Interface"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Custom primay \/ secondary \/ footer labels"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"✅ Detection of copied text \/ code from outside the app"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"app_screens_1.png"}]},{"type":"paragraph","inlineContent":[{"type":"image","identifier":"app_screens_2.png"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/getting-started"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/getting-started"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Getting-Started","interfaceLanguage":"swift"},"kind":"article","metadata":{"roleHeading":"Article","title":"Getting Started - BJOTPViewController","role":"article","modules":[{"name":"BJOTPViewController"}]},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController"]]},"seeAlsoSections":[{"title":"Articles","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage"],"generated":true}],"references":{"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[{"type":"text","text":"Welcome to the Developer Documentation of BJOTPViewController"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"},"app_screens_1.png":{"alt":"App Screens 1","type":"image","identifier":"app_screens_1.png","variants":[{"url":"\/images\/app_screens_1.png","traits":["1x","light"]},{"url":"\/images\/app_screens_1~dark.png","traits":["1x","dark"]}]},"app_screens_2.png":{"alt":"App Screens 2","type":"image","identifier":"app_screens_2.png","variants":[{"url":"\/images\/app_screens_2.png","traits":["1x","light"]},{"url":"\/images\/app_screens_2~dark.png","traits":["1x","dark"]}]},"doc://BJOTPViewController/documentation/BJOTPViewController/Usage":{"role":"collectionGroup","title":"Usage - BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","kind":"article","type":"topic","url":"\/documentation\/bjotpviewcontroller\/usage"},"banner.png":{"alt":"BJOTPViewController Banner","type":"image","identifier":"banner.png","variants":[{"url":"\/images\/banner.png","traits":["1x","light"]}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Articles","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage"],"generated":true}]}],"traits":[{"interfaceLanguage":"occ"}]}]}