{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Installation","level":2,"type":"heading","text":"Installation"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"In Xcode project, go to "},{"type":"strong","inlineContent":[{"type":"text","text":"File"}]},{"type":"text","text":" → "},{"type":"strong","inlineContent":[{"type":"text","text":"Swift Packages"}]},{"type":"text","text":" → "},{"type":"strong","inlineContent":[{"type":"text","text":"Add Package Dependency…"}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Paste the repo URL: https:\/\/github.com\/BadhanGanesh\/BJOTPViewController.git"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Follow onscreen instructions for choosing the package options and targets you want to add the dependency to - but make sure you always consider choosing the latest version for the best experience - and click "},{"type":"strong","inlineContent":[{"type":"text","text":"Finish"}]},{"type":"text","text":" when you’re done."}]}]}]},{"anchor":"Presentation","level":2,"type":"heading","text":"Presentation"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Here is how you can quickly present an otp view controller with a heading and maximum number of characters for the otp."}]},{"type":"codeListing","syntax":"swift","code":["import BJOTPViewController","","\/\/ Initialise view controller","let oneTimePasswordVC = BJOTPViewController.init(withHeading: \"Two Factor Authentication\",","                                      withNumberOfCharacters: 6,","                                                    delegate: self)","\/\/ Present it","self.present(oneTimePasswordVC, animated: true, completion: nil)"]},{"anchor":"Example-Code","level":2,"type":"heading","text":"Example Code"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The following snippet can be used as is to create and configire an otp view controller"}]},{"type":"codeListing","syntax":"swift","code":["import UIKit","import BJOTPViewController","","class ViewController: UIViewController {","    ","    var otpScreen: BJOTPViewController?","    ","    @IBAction func onModalButtonTap(_ sender: UIButton) {","        ","        \/\/Title","        let heading: String = \"Two Factor Authentication\"","        ","        \/\/\/Initialize viewcontroller","        self.otpScreen = BJOTPViewController(withHeading: heading,","                                            withNumberOfCharacters: 6,","                                            delegate: self)","        ","        \/\/\/Configuration","        configure(otpScreen)","        ","        \/\/\/Present view controller modally","        present(self.otpScreen!, animated: true)","        ","    }","    ","    @IBAction func onPushButtonTap(_ sender: UIButton) {","        ","        \/\/Title","        let heading: String = \"Two Factor Authentication\"","        ","        \/\/\/Initialize viewcontroller","        self.otpScreen = BJOTPViewController(withHeading: heading,","                                             withNumberOfCharacters: 6,","                                             delegate: self)","        ","        \/\/\/Configuration","        configure(otpScreen)","        ","        \/\/\/Push view controller","        navigationController?.pushViewController(otpScreen!, animated: true)","        ","    }","    ","}","","\/**"," * Making view controller conform to `BJOTPViewControllerDelegate` protocol."," *"," * These delegate methods are key to handling the entered otp string"," * and other events in the view controller."," *\/","extension ViewController: BJOTPViewControllerDelegate {","    ","    func didClose(_ viewController: BJOTPViewController) {","        \/\/\/option-click on the method name above to see more details about it.","        self.otpScreen = nil","    }","    ","    func authenticate(_ otp: String, from viewController: BJOTPViewController) {","        \/\/\/option-click on the method name above to see more details about it.","    }","    ","    func didTap(footer button: UIButton, from viewController: BJOTPViewController) {","        \/\/\/option-click on the method name above to see more details about it.","    }","    ","}","","extension ViewController {","    func configure(_ otpScreen: BJOTPViewController?) {","        ","        guard let otpScreen = otpScreen else { return }","        ","        let imageName: String = [\"logo.xbox\", \"logo.playstation\"].randomElement()!","        let primaryLabel: String = \"Enter One Time Code\"","        let secondaryLabel: String = \"A message with a verification code has been sent to your devices. Enter the code to continue.\"","        let buttonTitle: String = \"LOGIN SECURELY\"","        ","        \/\/Set titles and options","        otpScreen.openKeyboadDuringStartup = true","        otpScreen.accentColor = [.systemRed, .systemBlue].randomElement()!","        otpScreen.primaryHeaderTitle = primaryLabel","        otpScreen.secondaryHeaderTitle = secondaryLabel","        otpScreen.footerTitle = \"Didn't get verification code?\"","        otpScreen.shouldFooterBehaveAsButton = true","        otpScreen.authenticateButtonTitle = buttonTitle","        ","        if #available(iOS 13.0, *) {","            otpScreen.brandImage = .init(systemName: imageName)?.withTintColor(UITraitCollection.current.userInterfaceStyle == .dark ? .white : .black).withRenderingMode(.alwaysOriginal)","        }","        ","    }","}","",""]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/bjotpviewcontroller\/usage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/bjotpviewcontroller\/usage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/Usage","interfaceLanguage":"swift"},"topicSections":[{"title":"All Properties","abstract":[{"type":"text","text":"See below for an exhaustive list of all the properties available"}],"identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]},{"title":"Protocols","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate"]}],"kind":"article","metadata":{"modules":[{"name":"BJOTPViewController"}],"role":"collectionGroup","title":"Usage - BJOTPViewController"},"hierarchy":{"paths":[["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController"]]},"references":{"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewController":{"role":"symbol","title":"BJOTPViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewController"}],"abstract":[{"type":"text","text":"A simple and neat-looking view controller that lets you type in OTPs quick and easy"}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewController"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontroller"},"doc://BJOTPViewController/documentation/BJOTPViewController/BJOTPViewControllerDelegate":{"role":"symbol","title":"BJOTPViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"BJOTPViewControllerDelegate"}],"abstract":[{"type":"text","text":"This protocol declares methods that are essential to use "},{"type":"reference","isActive":true,"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"},{"type":"text","text":". They are used to handle button taps that happen during various scenarios, for example close button tap action."}],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BJOTPViewControllerDelegate"}],"url":"\/documentation\/bjotpviewcontroller\/bjotpviewcontrollerdelegate"},"doc://BJOTPViewController/documentation/BJOTPViewController":{"role":"collection","title":"BJOTPViewController","abstract":[],"identifier":"doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController","kind":"symbol","type":"topic","url":"\/documentation\/bjotpviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"All Properties","abstract":[{"type":"text","text":"See below for an exhaustive list of all the properties available"}],"identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewController"]},{"title":"Protocols","identifiers":["doc:\/\/BJOTPViewController\/documentation\/BJOTPViewController\/BJOTPViewControllerDelegate"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/title","value":"BJOTPViewController"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewController\/fragments","value":[{"kind":"identifier","text":"BJOTPViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate\/title","value":"BJOTPViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1BJOTPViewController~1documentation~1BJOTPViewController~1BJOTPViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"BJOTPViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}